name = "rc-pulse"
compatibility_date = "2024-09-23"
pages_build_output_dir = "./dist"

[vars]
RINGCENTRAL_SERVER_URL = "https://platform.ringcentral.com"

[[services]]
binding = "BACKEND"
service = "rc-pulse-backend"
